/*
	GetRedirectDataExample.m
	Provides example and test runs the service's proxy methods.
	Generated by SudzC.com
*/
#import "GetRedirectDataExample.h"
#import "GetRedirectData.h"
#import "comAppDelegate.h"

@implementation GetRedirectDataExample

- (void)run{
	// Create the service
    comAppDelegate *d = (comAppDelegate*)[[UIApplication sharedApplication] delegate];

	GetRedirectData* service = [GetRedirectData service];
	service.logging = YES;
	service.username = [d.defaults stringForKey:@"username"];
	service.password = [d.defaults stringForKey:@"password"];
	// Returns NSString*. 
	[service GetInfo:self action:@selector(GetInfoHandler:) myCode: @"GETREDIRECTINFO" myValue: @""];
}

	

// Handle the response from GetInfo.
		
- (void) GetInfoHandler: (id) value {

    comAppDelegate *d = (comAppDelegate*)[[UIApplication sharedApplication] delegate];
	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"ERROR: %@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"FAULT: %@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"GetInfo returned the value: %@", result);
    
    d.URLSOAP = result;
    [d getSOAP]; 
}
	

@end
		