/*
	GetServiceServiceGateExample.h
	Provides example and test runs the service's proxy methods.
	Generated by SudzC.com
*/
#import "GetServiceServiceGate.h"

@interface GetServiceServiceGateExample : NSObject;

@property (readonly, strong, nonatomic) GetServiceServiceGate* service;
@property (readonly, strong, nonatomic) NSString *sessionToken;

-(void)run;
@end
		